import type {
  IInventoryAccessoryItem,
  IInventoryArmorItem,
  IInventoryItem,
} from '../types/Inventory';

export const ALL_ITEMS: IInventoryItem[] | IInventoryArmorItem[] = [
  {
    id: 'Amber',
    image: 'Amber.png',
    title: 'Amber',
    type: 'craft',
    amount: 1,
    price: 100,
    description: 'Some description',
    rarity: 'common',
  },
  {
    id: 'AstralAlloy',
    image: 'AstralAlloy.png',
    title: 'Astral Alloy',
    type: 'craft',
    amount: 1,
    price: 100,
    description: 'Some description',
    rarity: 'common',
  },
  {
    id: 'BlackOrb',
    image: 'BlackOrb.png',
    title: 'Black Orb',
    type: 'craft',
    amount: 1,
    price: 100,
    description: 'Some description',
    rarity: 'common',
  },
  {
    id: 'ChainLink',
    image: 'ChainLink.png',
    title: 'Chain Link',
    type: 'craft',
    amount: 1,
    price: 100,
    description: 'Some description',
    rarity: 'common',
  },
  {
    id: 'Crystall',
    image: 'Crystall.png',
    title: 'Crystall',
    type: 'craft',
    amount: 1,
    price: 100,
    description: 'Some description',
    rarity: 'common',
  },
  {
    id: 'Frostdust',
    image: 'Frostdust.png',
    title: 'Frostdust',
    type: 'craft',
    amount: 1,
    price: 100,
    description: 'Some description',
    rarity: 'common',
  },
  {
    id: 'Glowstone',
    image: 'Glowstone.png',
    title: 'Glowstone',
    type: 'craft',
    amount: 1,
    price: 100,
    description: 'Some description',
    rarity: 'common',
  },
  {
    id: 'ManaBark',
    image: 'ManaBark.png',
    title: 'Mana Bark',
    type: 'craft',
    amount: 1,
    price: 100,
    description: 'Some description',
    rarity: 'common',
  },
  {
    id: 'Pearl',
    image: 'Pearl.png',
    title: 'Pearl',
    type: 'craft',
    amount: 1,
    price: 100,
    description: 'Some description',
    rarity: 'common',
  },
  {
    id: 'PhoenixEmber',
    image: 'PhoenixEmber.png',
    title: 'Phoenix Ember',
    type: 'craft',
    amount: 1,
    price: 100,
    description: 'Some description',
    rarity: 'common',
  },
  {
    id: 'ReedSilk',
    image: 'ReedSilk.png',
    title: 'Reed Silk',
    type: 'craft',
    amount: 1,
    price: 100,
    description: 'Some description',
    rarity: 'common',
  },
  {
    id: 'ReinforcedPadding',
    image: 'ReinforcedPadding.png',
    title: 'Reinforced Padding',
    type: 'craft',
    amount: 1,
    price: 100,
    description: 'Some description',
    rarity: 'common',
  },
  {
    id: 'Resin',
    image: 'Resin.png',
    title: 'Resin',
    type: 'craft',
    amount: 1,
    price: 100,
    description: 'Some description',
    rarity: 'common',
  },
  {
    id: 'Rune',
    image: 'Rune.png',
    title: 'Rune',
    type: 'craft',
    amount: 1,
    price: 100,
    description: 'Some description',
    rarity: 'common',
  },
  {
    id: 'SerpentScale',
    image: 'SerpentScale.png',
    title: 'Serpent Scale',
    type: 'craft',
    amount: 1,
    price: 100,
    description: 'Some description',
    rarity: 'common',
  },
  {
    id: 'ShadowstepLeather',
    image: 'ShadowstepLeather.png',
    title: 'Shadowstep Leather',
    type: 'craft',
    amount: 1,
    price: 100,
    description: 'Some description',
    rarity: 'common',
  },
  {
    id: 'ShardofIllusion',
    image: 'ShardofIllusion.png',
    title: 'Shard of Illusion',
    type: 'craft',
    amount: 1,
    price: 100,
    description: 'Some description',
    rarity: 'common',
  },
  {
    id: 'Shell',
    image: 'Shell.png',
    title: 'Shell',
    type: 'craft',
    amount: 1,
    price: 100,
    description: 'Some description',
    rarity: 'common',
  },
  {
    id: 'SilverThread',
    image: 'SilverThread.png',
    title: 'Silver Thread',
    type: 'craft',
    amount: 1,
    price: 100,
    description: 'Some description',
    rarity: 'common',
  },
  {
    id: 'SoulStone1',
    image: 'SoulStone1.png',
    title: 'Soul Stone 1',
    type: 'craft',
    amount: 1,
    price: 100,
    description: 'Some description',
    rarity: 'common',
  },
  {
    id: 'SoulStone2',
    image: 'SoulStone2.png',
    title: 'Soul Stone 2',
    type: 'craft',
    amount: 1,
    price: 100,
    description: 'Some description',
    rarity: 'common',
  },
  {
    id: 'SoulStone3',
    image: 'SoulStone3.png',
    title: 'Soul Stone 3',
    type: 'craft',
    amount: 1,
    price: 100,
    description: 'Some description',
    rarity: 'common',
  },
  {
    id: 'SoulStone4',
    image: 'SoulStone4.png',
    title: 'Soul Stone 4',
    type: 'craft',
    amount: 1,
    price: 100,
    description: 'Some description',
    rarity: 'common',
  },
  {
    id: 'SoulStone5',
    image: 'SoulStone5.png',
    title: 'Soul Stone 5',
    type: 'craft',
    amount: 1,
    price: 100,
    description: 'Some description',
    rarity: 'common',
  },
  {
    id: 'WaterEssence',
    image: 'WaterEssence.png',
    title: 'Water Essence',
    type: 'craft',
    amount: 1,
    price: 100,
    description: 'Some description',
    rarity: 'common',
  },
  {
    id: 'WerewolfFang',
    image: 'WerewolfFang.png',
    title: 'Werewolf Fang',
    type: 'craft',
    amount: 1,
    price: 100,
    description: 'Some description',
    rarity: 'common',
  },
];

export const ALL_ARMOR_ITEMS: IInventoryArmorItem[] = [
  {
    id: 'MysticRobe',
    image: 'MysticRobe.png',
    title: 'Mystic Robe',
    type: 'armor',
    wearableSlot: 'arms',
    amount: 1,
    price: 500,
    description: 'A powerful robe imbued with ancient magic',
    rarity: 'uncommon',
    level: 5,
    buff: [
      { effect: 'atk', value: 15 },
      { effect: 'hp', value: 50 },
    ],
    improvementRequirements: [
      { item: ALL_ITEMS[0]!, amount: 3 },
      { item: ALL_ITEMS[6]!, amount: 2 },
    ],
    wearRequirements: [
      { requirement: 'Level', value: 5 },
      { requirement: 'Intelligence', value: 20 },
    ],
  },
  {
    id: 'ShadowLeggings',
    image: 'ShadowLeggings.png',
    title: 'Shadow Leggings',
    type: 'armor',
    wearableSlot: 'legs',
    amount: 1,
    price: 450,
    description: 'Leggings woven from shadows themselves',
    rarity: 'uncommon',
    level: 4,
    buff: [
      { effect: 'dodge', value: 12 },
      { effect: 'accuracy', value: 8 },
    ],
    improvementRequirements: [
      { item: ALL_ITEMS[15]!, amount: 2 },
      { item: ALL_ITEMS[18]!, amount: 4 },
    ],
    wearRequirements: [
      { requirement: 'Level', value: 4 },
      { requirement: 'Dexterity', value: 18 },
    ],
  },
  {
    id: 'AstralBelt',
    image: 'AstralBelt.png',
    title: 'Astral Belt',
    type: 'armor',
    wearableSlot: 'belt',
    amount: 1,
    price: 350,
    description: 'A belt infused with astral energy',
    rarity: 'common',
    level: 3,
    buff: [
      { effect: 'hp', value: 50 },
      { effect: 'accuracy', value: 5 },
    ],
    improvementRequirements: [
      { item: ALL_ITEMS[1]!, amount: 2 },
      { item: ALL_ITEMS[4]!, amount: 3 },
    ],
    wearRequirements: [
      { requirement: 'Level', value: 3 },
      { requirement: 'Intelligence', value: 15 },
    ],
  },
];

export const ALL_ARMOR_ITEMS_WITH_SLOTS = ALL_ARMOR_ITEMS.map((item) => ({
  ...item,
  title: `${item.title} (${item.wearableSlot})`,
}));

export const ALL_ACCESSORIES: IInventoryAccessoryItem[] = [
  {
    id: 'MoonlightGem',
    image: 'MoonlightGem.png',
    title: 'Moonlight Gem',
    type: 'accessory',
    wearableSlot: 'gem',
    amount: 1,
    price: 600,
    description: 'A radiant gem infused with lunar energy',
    rarity: 'uncommon',
    level: 6,
    buff: [
      { effect: 'atk', value: 18 },
      { effect: 'hp', value: 80 },
    ],
    improvementRequirements: [
      { item: ALL_ITEMS[4]!, amount: 5 },
      { item: ALL_ITEMS[6]!, amount: 3 },
    ],
    wearRequirements: [
      { requirement: 'Level', value: 6 },
      { requirement: 'Intelligence', value: 25 },
    ],
  },
  {
    id: 'CrimsonGem',
    image: 'CrimsonGem.png',
    title: 'Crimson Gem',
    type: 'accessory',
    wearableSlot: 'gem',
    amount: 1,
    price: 550,
    description: 'A blood-red gem pulsing with raw power',
    rarity: 'uncommon',
    level: 5,
    buff: [
      { effect: 'atk', value: 20 },
      { effect: 'crit', value: 8 },
    ],
    improvementRequirements: [
      { item: ALL_ITEMS[9]!, amount: 4 },
      { item: ALL_ITEMS[2]!, amount: 2 },
    ],
    wearRequirements: [
      { requirement: 'Level', value: 5 },
      { requirement: 'Strength', value: 22 },
    ],
  },
  {
    id: 'ShadowRing',
    image: 'ShadowRing.png',
    title: 'Shadow Ring',
    type: 'accessory',
    wearableSlot: 'ring',
    amount: 1,
    price: 480,
    description: 'A mysterious ring that bends shadows to your will',
    rarity: 'common',
    level: 4,
    buff: [
      { effect: 'accuracy', value: 15 },
      { effect: 'dodge', value: 12 },
    ],
    improvementRequirements: [
      { item: ALL_ITEMS[15]!, amount: 3 },
      { item: ALL_ITEMS[16]!, amount: 2 },
    ],
    wearRequirements: [
      { requirement: 'Level', value: 4 },
      { requirement: 'Dexterity', value: 18 },
    ],
  },
  {
    id: 'RuneRing',
    image: 'RuneRing.png',
    title: 'Rune Ring',
    type: 'accessory',
    wearableSlot: 'ring',
    amount: 1,
    price: 520,
    description: 'An ancient ring inscribed with powerful runes',
    rarity: 'uncommon',
    level: 5,
    buff: [
      { effect: 'def', value: 10 },
      { effect: 'hp', value: 40 },
    ],
    improvementRequirements: [
      { item: ALL_ITEMS[13]!, amount: 4 },
      { item: ALL_ITEMS[0]!, amount: 3 },
    ],
    wearRequirements: [
      { requirement: 'Level', value: 5 },
      { requirement: 'Intelligence', value: 20 },
    ],
  },
  {
    id: 'PhoenixNecklace',
    image: 'PhoenixNecklace.png',
    title: 'Phoenix Necklace',
    type: 'accessory',
    wearableSlot: 'necklace',
    amount: 1,
    price: 650,
    description: 'A necklace bearing the eternal flame of the phoenix',
    rarity: 'unique',
    level: 7,
    buff: [
      { effect: 'hp', value: 80 },
      { effect: 'def', value: 15 },
      { effect: 'atk', value: 10 },
    ],
    improvementRequirements: [
      { item: ALL_ITEMS[9]!, amount: 6 },
      { item: ALL_ITEMS[10]!, amount: 4 },
    ],
    wearRequirements: [
      { requirement: 'Level', value: 7 },
      { requirement: 'Vitality', value: 28 },
    ],
  },
  {
    id: 'FrostNecklace',
    image: 'FrostNecklace.png',
    title: 'Frost Necklace',
    type: 'accessory',
    wearableSlot: 'necklace',
    amount: 1,
    price: 580,
    description: 'A chilling necklace forged from eternal ice',
    rarity: 'uncommon',
    level: 6,
    buff: [
      { effect: 'atk', value: 22 },
      { effect: 'accuracy', value: 10 },
    ],
    improvementRequirements: [
      { item: ALL_ITEMS[5]!, amount: 5 },
      { item: ALL_ITEMS[24]!, amount: 3 },
    ],
    wearRequirements: [
      { requirement: 'Level', value: 6 },
      { requirement: 'Intelligence', value: 24 },
    ],
  },
  {
    id: 'SerpentNecklace',
    image: 'SerpentNecklace.png',
    title: 'Serpent Necklace',
    type: 'accessory',
    wearableSlot: 'necklace',
    amount: 1,
    price: 530,
    description: 'A sinister necklace crafted from serpent scales',
    rarity: 'uncommon',
    level: 5,
    buff: [
      { effect: 'atk', value: 18 },
      { effect: 'def', value: 10 },
    ],
    improvementRequirements: [
      { item: ALL_ITEMS[14]!, amount: 4 },
      { item: ALL_ITEMS[17]!, amount: 3 },
    ],
    wearRequirements: [
      { requirement: 'Level', value: 5 },
      { requirement: 'Dexterity', value: 20 },
    ],
  },
];

export const ALL_ACCESSORIES_WITH_SLOTS = ALL_ACCESSORIES.map((item) => ({
  ...item,
  title: `${item.title} (${item.wearableSlot})`,
}));
