import type { IInventoryArmor, IInventoryItem } from '../types/Inventory';

export const ALL_ITEMS: IInventoryItem[] | IInventoryArmor[] = [
  {
    id: 'Amber',
    image: 'Amber.png',
    title: 'Amber',
    type: 'craft',
    amount: 1,
    price: 100,
    description: 'Some description',
    rarity: 'common',
  },
  {
    id: 'AstralAlloy',
    image: 'AstralAlloy.png',
    title: 'Astral Alloy',
    type: 'craft',
    amount: 1,
    price: 100,
    description: 'Some description',
    rarity: 'common',
  },
  {
    id: 'BlackOrb',
    image: 'BlackOrb.png',
    title: 'Black Orb',
    type: 'craft',
    amount: 1,
    price: 100,
    description: 'Some description',
    rarity: 'common',
  },
  {
    id: 'ChainLink',
    image: 'ChainLink.png',
    title: 'Chain Link',
    type: 'craft',
    amount: 1,
    price: 100,
    description: 'Some description',
    rarity: 'common',
  },
  {
    id: 'Crystall',
    image: 'Crystall.png',
    title: 'Crystall',
    type: 'craft',
    amount: 1,
    price: 100,
    description: 'Some description',
    rarity: 'common',
  },
  {
    id: 'Frostdust',
    image: 'Frostdust.png',
    title: 'Frostdust',
    type: 'craft',
    amount: 1,
    price: 100,
    description: 'Some description',
    rarity: 'common',
  },
  {
    id: 'Glowstone',
    image: 'Glowstone.png',
    title: 'Glowstone',
    type: 'craft',
    amount: 1,
    price: 100,
    description: 'Some description',
    rarity: 'common',
  },
  {
    id: 'ManaBark',
    image: 'ManaBark.png',
    title: 'Mana Bark',
    type: 'craft',
    amount: 1,
    price: 100,
    description: 'Some description',
    rarity: 'common',
  },
  {
    id: 'Pearl',
    image: 'Pearl.png',
    title: 'Pearl',
    type: 'craft',
    amount: 1,
    price: 100,
    description: 'Some description',
    rarity: 'common',
  },
  {
    id: 'PhoenixEmber',
    image: 'PhoenixEmber.png',
    title: 'Phoenix Ember',
    type: 'craft',
    amount: 1,
    price: 100,
    description: 'Some description',
    rarity: 'common',
  },
  {
    id: 'ReedSilk',
    image: 'ReedSilk.png',
    title: 'Reed Silk',
    type: 'craft',
    amount: 1,
    price: 100,
    description: 'Some description',
    rarity: 'common',
  },
  {
    id: 'ReinforcedPadding',
    image: 'ReinforcedPadding.png',
    title: 'Reinforced Padding',
    type: 'craft',
    amount: 1,
    price: 100,
    description: 'Some description',
    rarity: 'common',
  },
  {
    id: 'Resin',
    image: 'Resin.png',
    title: 'Resin',
    type: 'craft',
    amount: 1,
    price: 100,
    description: 'Some description',
    rarity: 'common',
  },
  {
    id: 'Rune',
    image: 'Rune.png',
    title: 'Rune',
    type: 'craft',
    amount: 1,
    price: 100,
    description: 'Some description',
    rarity: 'common',
  },
  {
    id: 'SerpentScale',
    image: 'SerpentScale.png',
    title: 'Serpent Scale',
    type: 'craft',
    amount: 1,
    price: 100,
    description: 'Some description',
    rarity: 'common',
  },
  {
    id: 'ShadowstepLeather',
    image: 'ShadowstepLeather.png',
    title: 'Shadowstep Leather',
    type: 'craft',
    amount: 1,
    price: 100,
    description: 'Some description',
    rarity: 'common',
  },
  {
    id: 'ShardofIllusion',
    image: 'ShardofIllusion.png',
    title: 'Shard of Illusion',
    type: 'craft',
    amount: 1,
    price: 100,
    description: 'Some description',
    rarity: 'common',
  },
  {
    id: 'Shell',
    image: 'Shell.png',
    title: 'Shell',
    type: 'craft',
    amount: 1,
    price: 100,
    description: 'Some description',
    rarity: 'common',
  },
  {
    id: 'SilverThread',
    image: 'SilverThread.png',
    title: 'Silver Thread',
    type: 'craft',
    amount: 1,
    price: 100,
    description: 'Some description',
    rarity: 'common',
  },
  {
    id: 'SoulStone1',
    image: 'SoulStone1.png',
    title: 'Soul Stone 1',
    type: 'craft',
    amount: 1,
    price: 100,
    description: 'Some description',
    rarity: 'common',
  },
  {
    id: 'SoulStone2',
    image: 'SoulStone2.png',
    title: 'Soul Stone 2',
    type: 'craft',
    amount: 1,
    price: 100,
    description: 'Some description',
    rarity: 'common',
  },
  {
    id: 'SoulStone3',
    image: 'SoulStone3.png',
    title: 'Soul Stone 3',
    type: 'craft',
    amount: 1,
    price: 100,
    description: 'Some description',
    rarity: 'common',
  },
  {
    id: 'SoulStone4',
    image: 'SoulStone4.png',
    title: 'Soul Stone 4',
    type: 'craft',
    amount: 1,
    price: 100,
    description: 'Some description',
    rarity: 'common',
  },
  {
    id: 'SoulStone5',
    image: 'SoulStone5.png',
    title: 'Soul Stone 5',
    type: 'craft',
    amount: 1,
    price: 100,
    description: 'Some description',
    rarity: 'common',
  },
  {
    id: 'WaterEssence',
    image: 'WaterEssence.png',
    title: 'Water Essence',
    type: 'craft',
    amount: 1,
    price: 100,
    description: 'Some description',
    rarity: 'common',
  },
  {
    id: 'WerewolfFang',
    image: 'WerewolfFang.png',
    title: 'Werewolf Fang',
    type: 'craft',
    amount: 1,
    price: 100,
    description: 'Some description',
    rarity: 'common',
  },
];
