import type { IInventoryArmor, IInventoryItem } from '../types/Inventory';

export const ALL_ITEMS: IInventoryItem[] | IInventoryArmor[] = [
  {
    id: 'Amber',
    image: 'Amber.png',
    title: 'Amber',
    type: 'craft',
    amount: 1,
    price: 100,
    description: 'Some description',
    rarity: 'common',
  },
  {
    id: 'AstralAlloy',
    image: 'AstralAlloy.png',
    title: 'Astral Alloy',
    type: 'craft',
    amount: 1,
    price: 100,
    description: 'Some description',
    rarity: 'common',
  },
  {
    id: 'BlackOrb',
    image: 'BlackOrb.png',
    title: 'Black Orb',
    type: 'craft',
    amount: 1,
    price: 100,
    description: 'Some description',
    rarity: 'common',
  },
  {
    id: 'ChainLink',
    image: 'ChainLink.png',
    title: 'Chain Link',
    type: 'craft',
    amount: 1,
    price: 100,
    description: 'Some description',
    rarity: 'common',
  },
  {
    id: 'Crystall',
    image: 'Crystall.png',
    title: 'Crystall',
    type: 'craft',
    amount: 1,
    price: 100,
    description: 'Some description',
    rarity: 'common',
  },
  {
    id: 'Frostdust',
    image: 'Frostdust.png',
    title: 'Frostdust',
    type: 'craft',
    amount: 1,
    price: 100,
    description: 'Some description',
    rarity: 'common',
  },
  {
    id: 'Glowstone',
    image: 'Glowstone.png',
    title: 'Glowstone',
    type: 'craft',
    amount: 1,
    price: 100,
    description: 'Some description',
    rarity: 'common',
  },
  {
    id: 'ManaBark',
    image: 'ManaBark.png',
    title: 'Mana Bark',
    type: 'craft',
    amount: 1,
    price: 100,
    description: 'Some description',
    rarity: 'common',
  },
  {
    id: 'Pearl',
    image: 'Pearl.png',
    title: 'Pearl',
    type: 'craft',
    amount: 1,
    price: 100,
    description: 'Some description',
    rarity: 'common',
  },
  {
    id: 'PhoenixEmber',
    image: 'PhoenixEmber.png',
    title: 'Phoenix Ember',
    type: 'craft',
    amount: 1,
    price: 100,
    description: 'Some description',
    rarity: 'common',
  },
  {
    id: 'ReedSilk',
    image: 'ReedSilk.png',
    title: 'Reed Silk',
    type: 'craft',
    amount: 1,
    price: 100,
    description: 'Some description',
    rarity: 'common',
  },
  {
    id: 'ReinforcedPadding',
    image: 'ReinforcedPadding.png',
    title: 'Reinforced Padding',
    type: 'craft',
    amount: 1,
    price: 100,
    description: 'Some description',
    rarity: 'common',
  },
  {
    id: 'Resin',
    image: 'Resin.png',
    title: 'Resin',
    type: 'craft',
    amount: 1,
    price: 100,
    description: 'Some description',
    rarity: 'common',
  },
  {
    id: 'Rune',
    image: 'Rune.png',
    title: 'Rune',
    type: 'craft',
    amount: 1,
    price: 100,
    description: 'Some description',
    rarity: 'common',
  },
  {
    id: 'SerpentScale',
    image: 'SerpentScale.png',
    title: 'Serpent Scale',
    type: 'craft',
    amount: 1,
    price: 100,
    description: 'Some description',
    rarity: 'common',
  },
  {
    id: 'ShadowstepLeather',
    image: 'ShadowstepLeather.png',
    title: 'Shadowstep Leather',
    type: 'craft',
    amount: 1,
    price: 100,
    description: 'Some description',
    rarity: 'common',
  },
  {
    id: 'ShardofIllusion',
    image: 'ShardofIllusion.png',
    title: 'Shard of Illusion',
    type: 'craft',
    amount: 1,
    price: 100,
    description: 'Some description',
    rarity: 'common',
  },
  {
    id: 'Shell',
    image: 'Shell.png',
    title: 'Shell',
    type: 'craft',
    amount: 1,
    price: 100,
    description: 'Some description',
    rarity: 'common',
  },
  {
    id: 'SilverThread',
    image: 'SilverThread.png',
    title: 'Silver Thread',
    type: 'craft',
    amount: 1,
    price: 100,
    description: 'Some description',
    rarity: 'common',
  },
  {
    id: 'SoulStone1',
    image: 'SoulStone1.png',
    title: 'Soul Stone 1',
    type: 'craft',
    amount: 1,
    price: 100,
    description: 'Some description',
    rarity: 'common',
  },
  {
    id: 'SoulStone2',
    image: 'SoulStone2.png',
    title: 'Soul Stone 2',
    type: 'craft',
    amount: 1,
    price: 100,
    description: 'Some description',
    rarity: 'common',
  },
  {
    id: 'SoulStone3',
    image: 'SoulStone3.png',
    title: 'Soul Stone 3',
    type: 'craft',
    amount: 1,
    price: 100,
    description: 'Some description',
    rarity: 'common',
  },
  {
    id: 'SoulStone4',
    image: 'SoulStone4.png',
    title: 'Soul Stone 4',
    type: 'craft',
    amount: 1,
    price: 100,
    description: 'Some description',
    rarity: 'common',
  },
  {
    id: 'SoulStone5',
    image: 'SoulStone5.png',
    title: 'Soul Stone 5',
    type: 'craft',
    amount: 1,
    price: 100,
    description: 'Some description',
    rarity: 'common',
  },
  {
    id: 'WaterEssence',
    image: 'WaterEssence.png',
    title: 'Water Essence',
    type: 'craft',
    amount: 1,
    price: 100,
    description: 'Some description',
    rarity: 'common',
  },
  {
    id: 'WerewolfFang',
    image: 'WerewolfFang.png',
    title: 'Werewolf Fang',
    type: 'craft',
    amount: 1,
    price: 100,
    description: 'Some description',
    rarity: 'common',
  },
];

export const ALL_ARMORYITEMS: IInventoryArmor[] = [
  {
    id: 'MysticRobe',
    image: 'MysticRobe.png',
    title: 'Mystic Robe',
    type: 'armor',
    wearableSlot: 'arms',
    amount: 1,
    price: 500,
    description: 'A powerful robe imbued with ancient magic',
    rarity: 'uncommon',
    level: 5,
    buff: [
      { effect: 'Magic Power', value: 15 },
      { effect: 'Mana Regeneration', value: 5 },
    ],
    improvementRequirements: [
      { item: ALL_ITEMS[0]!, amount: 3 },
      { item: ALL_ITEMS[6]!, amount: 2 },
    ],
    wearRequirements: [
      { requirement: 'Level', value: 5 },
      { requirement: 'Intelligence', value: 20 },
    ],
  },
  {
    id: 'ShadowLeggings',
    image: 'ShadowLeggings.png',
    title: 'Shadow Leggings',
    type: 'armor',
    wearableSlot: 'legs',
    amount: 1,
    price: 450,
    description: 'Leggings woven from shadows themselves',
    rarity: 'uncommon',
    level: 4,
    buff: [
      { effect: 'Agility', value: 12 },
      { effect: 'Stealth', value: 8 },
    ],
    improvementRequirements: [
      { item: ALL_ITEMS[15]!, amount: 2 },
      { item: ALL_ITEMS[18]!, amount: 4 },
    ],
    wearRequirements: [
      { requirement: 'Level', value: 4 },
      { requirement: 'Dexterity', value: 18 },
    ],
  },
  {
    id: 'PhoenixRing',
    image: 'PhoenixRing.png',
    title: 'Phoenix Ring',
    type: 'armor',
    wearableSlot: 'ring',
    amount: 1,
    price: 800,
    description: 'A ring forged from phoenix essence',
    rarity: 'unique',
    level: 8,
    buff: [
      { effect: 'Fire Resistance', value: 25 },
      { effect: 'Health Regeneration', value: 10 },
    ],
    improvementRequirements: [
      { item: ALL_ITEMS[9]!, amount: 5 },
      { item: ALL_ITEMS[13]!, amount: 3 },
    ],
    wearRequirements: [
      { requirement: 'Level', value: 8 },
      { requirement: 'Wisdom', value: 25 },
    ],
  },
  {
    id: 'AstralBelt',
    image: 'AstralBelt.png',
    title: 'Astral Belt',
    type: 'armor',
    wearableSlot: 'belt',
    amount: 1,
    price: 350,
    description: 'A belt infused with astral energy',
    rarity: 'common',
    level: 3,
    buff: [
      { effect: 'Max Mana', value: 50 },
      { effect: 'Spell Speed', value: 5 },
    ],
    improvementRequirements: [
      { item: ALL_ITEMS[1]!, amount: 2 },
      { item: ALL_ITEMS[4]!, amount: 3 },
    ],
    wearRequirements: [
      { requirement: 'Level', value: 3 },
      { requirement: 'Intelligence', value: 15 },
    ],
  },
  {
    id: 'SerpentNecklace',
    image: 'SerpentNecklace.png',
    title: 'Serpent Necklace',
    type: 'armor',
    wearableSlot: 'necklace',
    amount: 1,
    price: 600,
    description: 'A necklace adorned with serpent scales',
    rarity: 'uncommon',
    level: 6,
    buff: [
      { effect: 'Poison Resistance', value: 20 },
      { effect: 'Defense', value: 15 },
    ],
    improvementRequirements: [
      { item: ALL_ITEMS[14]!, amount: 4 },
      { item: ALL_ITEMS[8]!, amount: 2 },
    ],
    wearRequirements: [
      { requirement: 'Level', value: 6 },
      { requirement: 'Constitution', value: 22 },
    ],
  },
];