import type {
  IMarketBuyItem,
  IMarketHistoryItem,
  IMarketSellingItem,
} from '../types/IMarket';
import {
  ALL_ITEMS,
  ALL_ARMOR_ITEMS,
  ALL_ACCESSORIES,
} from './items';

export const MARKET_CATEGORY_OPTIONS = [
  { value: 'all', label: 'All' },
  { value: 'crafting', label: 'Crafting Items' },
  { value: 'crystals', label: 'Crystals' },
  { value: 'gear_archer', label: 'Gear: Archer' },
  { value: 'gear_duelist', label: 'Gear: Duelist' },
  { value: 'gear_sorcerer', label: 'Gear: Sorcerer' },
];

export const MARKET_BUY_SORT_OPTIONS = [
  { value: 'all_time', label: 'All time' },
  { value: 'new_to_old', label: 'From new to old' },
  { value: 'old_to_new', label: 'From old to new' },
  { value: 'price_high', label: 'Price: From high to low' },
  { value: 'price_low', label: 'Price: From low to high' },
  { value: 'only_gold', label: 'Only for gold' },
  { value: 'only_usdc', label: 'Only for USDC' },
];

export const MARKET_HISTORY_SORT_OPTIONS = [
  { value: 'all_time', label: 'All time' },
  { value: 'last_24h', label: 'Last 24 hours' },
  { value: 'last_week', label: 'Last week' },
  { value: 'last_month', label: 'Last month' },
  { value: 'price_low', label: 'Price: From low to high' },
  { value: 'price_high', label: 'Price: From high to low' },
  { value: 'only_gold', label: 'Only for gold' },
  { value: 'only_usdc', label: 'Only for USDC' },
];

export const MARKET_HISTORY_STATUS_OPTIONS = [
  { value: 'all', label: 'All' },
  { value: 'bought', label: 'Bought' },
  { value: 'sold', label: 'Sold' },
];

export const MARKET_BUY_ITEMS: IMarketBuyItem[] = [
  {
    id: 'market_amber_1',
    title: 'Amber',
    level: 1,
    image: 'Amber.png',
    quantity: 5,
    type: 'crafting',
    price: 80,
    priceCurrency: 'gold',
    tooltipItem: ALL_ITEMS[0],
  },
  {
    id: 'market_astral_alloy_1',
    title: 'Astral Alloy',
    level: 2,
    image: 'AstralAlloy.png',
    quantity: 3,
    type: 'crafting',
    price: 120,
    priceCurrency: 'gold',
    tooltipItem: ALL_ITEMS[1],
  },
  {
    id: 'market_phoenix_ember_1',
    title: 'Phoenix Ember',
    level: 4,
    image: 'PhoenixEmber.png',
    quantity: 2,
    type: 'crafting',
    price: 250,
    priceCurrency: 'gold',
    tooltipItem: ALL_ITEMS[9],
  },
  {
    id: 'market_rune_1',
    title: 'Rune',
    level: 3,
    image: 'Rune.png',
    quantity: 7,
    type: 'crafting',
    price: 95,
    priceCurrency: 'gold',
    tooltipItem: ALL_ITEMS[13],
  },
  {
    id: 'market_serpent_scale_1',
    title: 'Serpent Scale',
    level: 3,
    image: 'SerpentScale.png',
    quantity: 4,
    type: 'crafting',
    price: 110,
    priceCurrency: 'gold',
    tooltipItem: ALL_ITEMS[14],
  },
  {
    id: 'market_frostdust_1',
    title: 'Frostdust',
    level: 2,
    image: 'Frostdust.png',
    quantity: 10,
    type: 'crafting',
    price: 60,
    priceCurrency: 'gold',
    tooltipItem: ALL_ITEMS[5],
  },
  {
    id: 'market_crystal_1',
    title: 'Crystal',
    level: 1,
    image: 'Crystall.png',
    quantity: 8,
    type: 'crystals',
    price: 150,
    priceCurrency: 'gold',
    tooltipItem: ALL_ITEMS[4],
  },
  {
    id: 'market_soulstone1_1',
    title: 'Soul Stone I',
    level: 2,
    image: 'SoulStone1.png',
    quantity: 3,
    type: 'crystals',
    price: 200,
    priceCurrency: 'gold',
    tooltipItem: ALL_ITEMS[19],
  },
  {
    id: 'market_soulstone3_1',
    title: 'Soul Stone III',
    level: 4,
    image: 'SoulStone3.png',
    quantity: 2,
    type: 'crystals',
    price: 380,
    priceCurrency: 'gold',
    tooltipItem: ALL_ITEMS[21],
  },
  {
    id: 'market_moonlight_gem_1',
    title: 'Moonlight Gem',
    level: 6,
    image: 'MoonlightGem.png',
    quantity: 1,
    type: 'crystals',
    price: 5,
    priceCurrency: 'usdc',
    tooltipItem: ALL_ACCESSORIES[0],
  },
  {
    id: 'market_mystic_robe_1',
    title: 'Mystic Robe',
    level: 5,
    image: 'MysticRobe.png',
    quantity: 1,
    type: 'gear_sorcerer',
    price: 500,
    priceCurrency: 'gold',
    tooltipItem: ALL_ARMOR_ITEMS[0],
  },
  {
    id: 'market_astral_belt_1',
    title: 'Astral Belt',
    level: 3,
    image: 'AstralBelt.png',
    quantity: 1,
    type: 'gear_sorcerer',
    price: 350,
    priceCurrency: 'gold',
    tooltipItem: ALL_ARMOR_ITEMS[2],
  },
  {
    id: 'market_frost_necklace_1',
    title: 'Frost Necklace',
    level: 6,
    image: 'FrostNecklace.png',
    quantity: 1,
    type: 'gear_sorcerer',
    price: 8,
    priceCurrency: 'usdc',
    tooltipItem: ALL_ACCESSORIES[5],
  },
  {
    id: 'market_shadow_leggings_1',
    title: 'Shadow Leggings',
    level: 4,
    image: 'ShadowLeggings.png',
    quantity: 1,
    type: 'gear_duelist',
    price: 450,
    priceCurrency: 'gold',
    tooltipItem: ALL_ARMOR_ITEMS[1],
  },
  {
    id: 'market_shadow_ring_1',
    title: 'Shadow Ring',
    level: 4,
    image: 'ShadowRing.png',
    quantity: 1,
    type: 'gear_duelist',
    price: 480,
    priceCurrency: 'gold',
    tooltipItem: ALL_ACCESSORIES[2],
  },
  {
    id: 'market_serpent_necklace_1',
    title: 'Serpent Necklace',
    level: 5,
    image: 'SerpentNecklace.png',
    quantity: 1,
    type: 'gear_duelist',
    price: 6,
    priceCurrency: 'usdc',
    tooltipItem: ALL_ACCESSORIES[6],
  },
  {
    id: 'market_rune_ring_1',
    title: 'Rune Ring',
    level: 5,
    image: 'RuneRing.png',
    quantity: 1,
    type: 'gear_archer',
    price: 520,
    priceCurrency: 'gold',
    tooltipItem: ALL_ACCESSORIES[3],
  },
  {
    id: 'market_phoenix_necklace_1',
    title: 'Phoenix Necklace',
    level: 7,
    image: 'PhoenixNecklace.png',
    quantity: 1,
    type: 'gear_archer',
    price: 12,
    priceCurrency: 'usdc',
    tooltipItem: ALL_ACCESSORIES[4],
  },
  {
    id: 'market_crimson_gem_1',
    title: 'Crimson Gem',
    level: 5,
    image: 'CrimsonGem.png',
    quantity: 1,
    type: 'gear_archer',
    price: 550,
    priceCurrency: 'gold',
    tooltipItem: ALL_ACCESSORIES[1],
  },
];

export const MARKET_HISTORY_ITEMS: IMarketHistoryItem[] = [
  {
    id: 'hist_1',
    title: 'Amber',
    level: 1,
    image: 'Amber.png',
    quantity: 3,
    type: 'crafting',
    price: 80,
    priceCurrency: 'gold',
    date: '2026-03-04T10:30:00Z',
    status: 'bought',
  },
  {
    id: 'hist_2',
    title: 'Crystal',
    level: 1,
    image: 'Crystall.png',
    quantity: 2,
    type: 'crystals',
    price: 150,
    priceCurrency: 'gold',
    date: '2026-03-04T08:15:00Z',
    status: 'sold',
  },
  {
    id: 'hist_3',
    title: 'Mystic Robe',
    level: 5,
    image: 'MysticRobe.png',
    quantity: 1,
    type: 'gear_sorcerer',
    price: 500,
    priceCurrency: 'gold',
    date: '2026-03-03T20:45:00Z',
    status: 'bought',
  },
  {
    id: 'hist_4',
    title: 'Soul Stone I',
    level: 2,
    image: 'SoulStone1.png',
    quantity: 4,
    type: 'crystals',
    price: 200,
    priceCurrency: 'gold',
    date: '2026-03-03T14:22:00Z',
    status: 'sold',
  },
  {
    id: 'hist_5',
    title: 'Moonlight Gem',
    level: 6,
    image: 'MoonlightGem.png',
    quantity: 1,
    type: 'crystals',
    price: 5,
    priceCurrency: 'usdc',
    date: '2026-03-02T18:00:00Z',
    status: 'bought',
  },
  {
    id: 'hist_6',
    title: 'Frostdust',
    level: 2,
    image: 'Frostdust.png',
    quantity: 10,
    type: 'crafting',
    price: 60,
    priceCurrency: 'gold',
    date: '2026-03-02T11:10:00Z',
    status: 'sold',
  },
  {
    id: 'hist_7',
    title: 'Shadow Leggings',
    level: 4,
    image: 'ShadowLeggings.png',
    quantity: 1,
    type: 'gear_duelist',
    price: 450,
    priceCurrency: 'gold',
    date: '2026-03-01T09:55:00Z',
    status: 'bought',
  },
  {
    id: 'hist_8',
    title: 'Rune',
    level: 3,
    image: 'Rune.png',
    quantity: 5,
    type: 'crafting',
    price: 95,
    priceCurrency: 'gold',
    date: '2026-02-28T16:40:00Z',
    status: 'sold',
  },
  {
    id: 'hist_9',
    title: 'Frost Necklace',
    level: 6,
    image: 'FrostNecklace.png',
    quantity: 1,
    type: 'gear_sorcerer',
    price: 8,
    priceCurrency: 'usdc',
    date: '2026-02-28T13:25:00Z',
    status: 'bought',
  },
  {
    id: 'hist_10',
    title: 'Astral Alloy',
    level: 2,
    image: 'AstralAlloy.png',
    quantity: 3,
    type: 'crafting',
    price: 120,
    priceCurrency: 'gold',
    date: '2026-02-27T21:00:00Z',
    status: 'sold',
  },
  {
    id: 'hist_11',
    title: 'Rune Ring',
    level: 5,
    image: 'RuneRing.png',
    quantity: 1,
    type: 'gear_archer',
    price: 520,
    priceCurrency: 'gold',
    date: '2026-02-27T10:05:00Z',
    status: 'bought',
  },
  {
    id: 'hist_12',
    title: 'Serpent Scale',
    level: 3,
    image: 'SerpentScale.png',
    quantity: 4,
    type: 'crafting',
    price: 110,
    priceCurrency: 'gold',
    date: '2026-02-26T17:30:00Z',
    status: 'sold',
  },
  {
    id: 'hist_13',
    title: 'Phoenix Necklace',
    level: 7,
    image: 'PhoenixNecklace.png',
    quantity: 1,
    type: 'gear_archer',
    price: 12,
    priceCurrency: 'usdc',
    date: '2026-02-25T12:20:00Z',
    status: 'bought',
  },
  {
    id: 'hist_14',
    title: 'Astral Belt',
    level: 3,
    image: 'AstralBelt.png',
    quantity: 1,
    type: 'gear_sorcerer',
    price: 350,
    priceCurrency: 'gold',
    date: '2026-02-24T08:45:00Z',
    status: 'sold',
  },
  {
    id: 'hist_15',
    title: 'Soul Stone III',
    level: 4,
    image: 'SoulStone3.png',
    quantity: 2,
    type: 'crystals',
    price: 380,
    priceCurrency: 'gold',
    date: '2026-02-23T19:15:00Z',
    status: 'bought',
  },
  {
    id: 'hist_16',
    title: 'Shadow Ring',
    level: 4,
    image: 'ShadowRing.png',
    quantity: 1,
    type: 'gear_duelist',
    price: 480,
    priceCurrency: 'gold',
    date: '2026-02-22T14:00:00Z',
    status: 'sold',
  },
  {
    id: 'hist_17',
    title: 'Phoenix Ember',
    level: 4,
    image: 'PhoenixEmber.png',
    quantity: 2,
    type: 'crafting',
    price: 250,
    priceCurrency: 'gold',
    date: '2026-02-21T09:30:00Z',
    status: 'bought',
  },
  {
    id: 'hist_18',
    title: 'Serpent Necklace',
    level: 5,
    image: 'SerpentNecklace.png',
    quantity: 1,
    type: 'gear_duelist',
    price: 6,
    priceCurrency: 'usdc',
    date: '2026-02-20T11:50:00Z',
    status: 'sold',
  },
  {
    id: 'hist_19',
    title: 'Crimson Gem',
    level: 5,
    image: 'CrimsonGem.png',
    quantity: 1,
    type: 'gear_archer',
    price: 550,
    priceCurrency: 'gold',
    date: '2026-02-19T16:10:00Z',
    status: 'bought',
  },
  {
    id: 'hist_20',
    title: 'Amber',
    level: 1,
    image: 'Amber.png',
    quantity: 7,
    type: 'crafting',
    price: 80,
    priceCurrency: 'gold',
    date: '2026-02-18T07:25:00Z',
    status: 'sold',
  },
];

export const MARKET_SELLING_SORT_OPTIONS = [
  { value: 'all_time', label: 'All time' },
  { value: 'new_to_old', label: 'From new to old' },
  { value: 'old_to_new', label: 'From old to new' },
  { value: 'price_high', label: 'Price: From high to low' },
  { value: 'price_low', label: 'Price: From low to high' },
  { value: 'only_gold', label: 'Only for gold' },
  { value: 'only_usdc', label: 'Only for USDC' },
];

export const MARKET_CURRENCY_OPTIONS = [
  { value: 'gold', label: 'Gold' },
  { value: 'usdc', label: 'USDC' },
];

export const MARKET_SELL_ITEM_TYPE_OPTIONS = [
  { value: 'crafting', label: 'Crafting Items' },
  { value: 'crystals', label: 'Crystals' },
  { value: 'gear_archer', label: 'Gear: Archer' },
  { value: 'gear_duelist', label: 'Gear: Duelist' },
  { value: 'gear_sorcerer', label: 'Gear: Sorcerer' },
];

const now = new Date('2026-03-04T20:00:00Z').getTime();

export const MARKET_SELLING_ITEMS: IMarketSellingItem[] = [
  {
    id: 'sell_1',
    title: 'Shadowstep Leather',
    level: 2,
    image: 'ShadowstepLeather.png',
    quantity: 35,
    type: 'crafting',
    price: 400,
    priceCurrency: 'gold',
    listedAt: new Date(now - 10 * 60 * 1000).toISOString(),
    status: 'on_sale',
  },
  {
    id: 'sell_2',
    title: 'Water Essence',
    level: 1,
    image: 'WaterEssence.png',
    quantity: 45,
    type: 'crafting',
    price: 400,
    priceCurrency: 'gold',
    listedAt: new Date(now - 54 * 60 * 1000).toISOString(),
    status: 'sold',
  },
  {
    id: 'sell_3',
    title: 'Chain Link',
    level: 1,
    image: 'ChainLink.png',
    quantity: 50,
    type: 'crafting',
    price: 400,
    priceCurrency: 'gold',
    listedAt: new Date(now - (1 * 60 + 3) * 60 * 1000).toISOString(),
    status: 'on_sale',
  },
  {
    id: 'sell_4',
    title: 'Pearl',
    level: 2,
    image: 'Pearl.png',
    quantity: 99,
    type: 'crafting',
    price: 400,
    priceCurrency: 'gold',
    listedAt: new Date(now - (10 * 60 + 15) * 60 * 1000).toISOString(),
    status: 'on_sale',
  },
  {
    id: 'sell_5',
    title: 'Astral Alloy',
    level: 2,
    image: 'AstralAlloy.png',
    quantity: 100,
    type: 'crafting',
    price: 20,
    priceCurrency: 'usdc',
    listedAt: new Date(now - (15 * 60 + 3) * 60 * 1000).toISOString(),
    status: 'sold',
  },
  {
    id: 'sell_6',
    title: 'Duelist Ring',
    level: 2,
    image: 'DuelistRing.png',
    quantity: 1,
    type: 'gear_duelist',
    price: 400,
    priceCurrency: 'gold',
    listedAt: new Date(now - (21 * 60 + 56) * 60 * 1000).toISOString(),
    status: 'sold',
  },
  {
    id: 'sell_7',
    title: 'Sorcerer Ring',
    level: 3,
    image: 'SorcererRing.png',
    quantity: 2,
    type: 'gear_sorcerer',
    price: 15,
    priceCurrency: 'usdc',
    listedAt: new Date(
      now - ((1 * 24 + 1) * 60 + 45) * 60 * 1000
    ).toISOString(),
    status: 'on_sale',
  },
  {
    id: 'sell_8',
    title: 'Archer Boots',
    level: 5,
    image: 'ArcherBoots.png',
    quantity: 1,
    type: 'gear_archer',
    price: 10,
    priceCurrency: 'usdc',
    listedAt: new Date(
      now - ((3 * 24 + 15) * 60 + 3) * 60 * 1000
    ).toISOString(),
    status: 'on_sale',
  },
];
