import type { IMarketBuyItem } from '../types/IMarket';

export const MARKET_BUY_ITEMS: IMarketBuyItem[] = [
  {
    id: 'market_amber_1',
    title: 'Amber',
    level: 1,
    image: 'Amber.png',
    quantity: 5,
    type: 'crafting',
    price: 80,
    priceCurrency: 'gold',
  },
  {
    id: 'market_astral_alloy_1',
    title: 'Astral Alloy',
    level: 2,
    image: 'AstralAlloy.png',
    quantity: 3,
    type: 'crafting',
    price: 120,
    priceCurrency: 'gold',
  },
  {
    id: 'market_phoenix_ember_1',
    title: 'Phoenix Ember',
    level: 4,
    image: 'PhoenixEmber.png',
    quantity: 2,
    type: 'crafting',
    price: 250,
    priceCurrency: 'gold',
  },
  {
    id: 'market_rune_1',
    title: 'Rune',
    level: 3,
    image: 'Rune.png',
    quantity: 7,
    type: 'crafting',
    price: 95,
    priceCurrency: 'gold',
  },
  {
    id: 'market_serpent_scale_1',
    title: 'Serpent Scale',
    level: 3,
    image: 'SerpentScale.png',
    quantity: 4,
    type: 'crafting',
    price: 110,
    priceCurrency: 'gold',
  },
  {
    id: 'market_frostdust_1',
    title: 'Frostdust',
    level: 2,
    image: 'Frostdust.png',
    quantity: 10,
    type: 'crafting',
    price: 60,
    priceCurrency: 'gold',
  },
  {
    id: 'market_crystal_1',
    title: 'Crystal',
    level: 1,
    image: 'Crystall.png',
    quantity: 8,
    type: 'crystals',
    price: 150,
    priceCurrency: 'gold',
  },
  {
    id: 'market_soulstone1_1',
    title: 'Soul Stone I',
    level: 2,
    image: 'SoulStone1.png',
    quantity: 3,
    type: 'crystals',
    price: 200,
    priceCurrency: 'gold',
  },
  {
    id: 'market_soulstone3_1',
    title: 'Soul Stone III',
    level: 4,
    image: 'SoulStone3.png',
    quantity: 2,
    type: 'crystals',
    price: 380,
    priceCurrency: 'gold',
  },
  {
    id: 'market_moonlight_gem_1',
    title: 'Moonlight Gem',
    level: 6,
    image: 'MoonlightGem.png',
    quantity: 1,
    type: 'crystals',
    price: 5,
    priceCurrency: 'usdc',
  },
  {
    id: 'market_mystic_robe_1',
    title: 'Mystic Robe',
    level: 5,
    image: 'MysticRobe.png',
    quantity: 1,
    type: 'gear_sorcerer',
    price: 500,
    priceCurrency: 'gold',
  },
  {
    id: 'market_astral_belt_1',
    title: 'Astral Belt',
    level: 3,
    image: 'AstralBelt.png',
    quantity: 1,
    type: 'gear_sorcerer',
    price: 350,
    priceCurrency: 'gold',
  },
  {
    id: 'market_frost_necklace_1',
    title: 'Frost Necklace',
    level: 6,
    image: 'FrostNecklace.png',
    quantity: 1,
    type: 'gear_sorcerer',
    price: 8,
    priceCurrency: 'usdc',
  },
  {
    id: 'market_shadow_leggings_1',
    title: 'Shadow Leggings',
    level: 4,
    image: 'ShadowLeggings.png',
    quantity: 1,
    type: 'gear_duelist',
    price: 450,
    priceCurrency: 'gold',
  },
  {
    id: 'market_shadow_ring_1',
    title: 'Shadow Ring',
    level: 4,
    image: 'ShadowRing.png',
    quantity: 1,
    type: 'gear_duelist',
    price: 480,
    priceCurrency: 'gold',
  },
  {
    id: 'market_serpent_necklace_1',
    title: 'Serpent Necklace',
    level: 5,
    image: 'SerpentNecklace.png',
    quantity: 1,
    type: 'gear_duelist',
    price: 6,
    priceCurrency: 'usdc',
  },
  {
    id: 'market_rune_ring_1',
    title: 'Rune Ring',
    level: 5,
    image: 'RuneRing.png',
    quantity: 1,
    type: 'gear_archer',
    price: 520,
    priceCurrency: 'gold',
  },
  {
    id: 'market_phoenix_necklace_1',
    title: 'Phoenix Necklace',
    level: 7,
    image: 'PhoenixNecklace.png',
    quantity: 1,
    type: 'gear_archer',
    price: 12,
    priceCurrency: 'usdc',
  },
  {
    id: 'market_crimson_gem_1',
    title: 'Crimson Gem',
    level: 5,
    image: 'CrimsonGem.png',
    quantity: 1,
    type: 'gear_archer',
    price: 550,
    priceCurrency: 'gold',
  },
];
